//! Postgres-backed `OpSessionRepository`.

use async_trait::async_trait;
use chrono::{DateTime, Duration, Utc};
use mokosh_auth_core::{
    AuthError, OpSession, OpSessionId, OpSessionRepository, TenantId, UserId,
};

use crate::conv::{db_err, ip_to_inet, OpSessionRow};
use crate::pool::AuthPool;

const SELECT_OP_SESSION: &str = r#"
    SELECT id, sid, user_id, tenant_id, created_at, last_active_at,
           expires_at, revoked_at, user_agent, ip, acr, amr
    FROM mokosh_auth.op_sessions
"#;

pub struct PgOpSessionRepository {
    pool: AuthPool,
}

impl PgOpSessionRepository {
    pub fn new(pool: AuthPool) -> Self {
        Self { pool }
    }
}

#[async_trait]
impl OpSessionRepository for PgOpSessionRepository {
    async fn create(
        &self,
        user_id: UserId,
        tenant_id: TenantId,
        ttl: Duration,
        user_agent: Option<&str>,
        ip: Option<std::net::IpAddr>,
        acr: &str,
        amr: &[String],
    ) -> Result<OpSession, AuthError> {
        // The `sid` is opaque, base64url, generated by the OIDC engine
        // and threaded through here via the public API. To keep the trait
        // contract simple, we generate it here using the same primitive.
        let sid = mokosh_auth_crypto::generate_opaque_token();
        let expires_at = Utc::now() + ttl;
        let row: OpSessionRow = sqlx::query_as(
            "INSERT INTO mokosh_auth.op_sessions
                (sid, user_id, tenant_id, expires_at, user_agent, ip, acr, amr)
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
             RETURNING id, sid, user_id, tenant_id, created_at, last_active_at,
                       expires_at, revoked_at, user_agent, ip, acr, amr",
        )
        .bind(&sid)
        .bind(user_id.0)
        .bind(tenant_id.0)
        .bind(expires_at)
        .bind(user_agent)
        .bind(ip_to_inet(ip))
        .bind(acr)
        .bind(amr)
        .fetch_one(self.pool.pg())
        .await
        .map_err(db_err)?;
        Ok(row.into())
    }

    async fn find_by_sid(&self, sid: &str) -> Result<Option<OpSession>, AuthError> {
        let row: Option<OpSessionRow> = sqlx::query_as(&format!(
            "{SELECT_OP_SESSION} WHERE sid = $1 AND revoked_at IS NULL"
        ))
        .bind(sid)
        .fetch_optional(self.pool.pg())
        .await
        .map_err(db_err)?;
        Ok(row.map(Into::into))
    }

    async fn touch(&self, id: OpSessionId, at: DateTime<Utc>) -> Result<(), AuthError> {
        sqlx::query(
            "UPDATE mokosh_auth.op_sessions
             SET last_active_at = $1
             WHERE id = $2 AND revoked_at IS NULL",
        )
        .bind(at)
        .bind(id.0)
        .execute(self.pool.pg())
        .await
        .map_err(db_err)?;
        Ok(())
    }

    async fn revoke(&self, id: OpSessionId, at: DateTime<Utc>) -> Result<(), AuthError> {
        sqlx::query(
            "UPDATE mokosh_auth.op_sessions
             SET revoked_at = $1
             WHERE id = $2 AND revoked_at IS NULL",
        )
        .bind(at)
        .bind(id.0)
        .execute(self.pool.pg())
        .await
        .map_err(db_err)?;
        Ok(())
    }

    async fn revoke_all_for_user(&self, user_id: UserId) -> Result<Vec<OpSessionId>, AuthError> {
        let rows: Vec<(uuid::Uuid,)> = sqlx::query_as(
            "UPDATE mokosh_auth.op_sessions
             SET revoked_at = NOW()
             WHERE user_id = $1 AND revoked_at IS NULL
             RETURNING id",
        )
        .bind(user_id.0)
        .fetch_all(self.pool.pg())
        .await
        .map_err(db_err)?;
        Ok(rows.into_iter().map(|(id,)| OpSessionId(id)).collect())
    }
}

